# Permalinks
permalink:           pretty

# Setup
title:               Claudine Chionh
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Claudine Chionh
  url:               http://claudinec.github.io/
  email:             info@claudinec.net

# Custom vars
version:             1.0.0
