# Permalinks
permalink:           /:year/:month/:day/:slug/

# Setup
title:               Claudine Chionh
baseurl:             ""
destination:         /keybase/public/claudinec
incremental:         true
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Claudine Chionh
  url:               http://claudinec.net/
  email:             cc@claudinec.net

# Custom vars
version:             1.0.0
