# Permalinks
permalink:           /:year/:month/:day/:slug.html

# Setup
title:               Claudine Chionh
baseurl:             ""
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Claudine Chionh
  url:               http://claudinec.github.io/
  email:             cc@claudinec.net

# Custom vars
version:             1.0.0
